### ISSUE TITLE
IP address is actually web address

### ISSUE THREAD

**Issue by siobhanellis** [watergate-ai/watergate-ha-custom-component#6]
When it asks for an ip address, it is actually a web address, starting with http:// This needs to be made clear in the configuration.

**Comment by nivek1612** [comment]
Yes that needs to be addressed either in docs or handled in the setup code. @adam-the-hero I can take a look if you like just let me know your preference.

**Comment by adam-the-hero** [comment]
I do not know what are the best practices there, but I would rather have some placeholder with http:// and validation for that. That would be the best option.

**Comment by nivek1612** [comment]
We could use the additions below. I'll need someone else to test them as deleting my instance to test means I will lose the data I'm collecting for the consumption comparisons.

async def async_step_user(
    self, user_input: dict[str, str] | None = None
) -> ConfigFlowResult:
    """Handle a flow initiated by the user."""
    errors: dict[str, str] = {}
    
    if user_input is not None:
        # Prepend 'http://' to the IP address if not already present
        ip_address = user_input[CONF_IP_ADDRESS]
        if not ip_address.startswith("http://"):
            ip_address = f"http://{ip_address}"
        
        # Update the user input with the modified IP address
        user_input[CONF_IP_ADDRESS] = ip_address

        if not await self.validate_connection(ip_address):
            errors[CONF_IP_ADDRESS] = "cannot_connect"
        else:
            return self.async_create_entry(
                data={**user_input, CONF_WEBHOOK_ID: webhook_generate_id()},
                title=SONIC,
            )

    return self.async_show_form(
        step_id="user", data_schema=WATERGATE_SCHEMA, errors=errors
    )

**Comment by adam-the-hero** [comment]
Well, I think I would rather go with validation instead of doing some magic in the backend.

**Comment by nivek1612** [comment]
fair I'll have another look later

**Comment by nivek1612** [comment]
how about 
```
"""Config flow for Watergate."""

import logging

import voluptuous as vol
from watergate_local_api.watergate_api import (
    WatergateApiException,
    WatergateLocalApiClient,
)

from homeassistant.components.webhook import async_generate_id as webhook_generate_id
from homeassistant.config_entries import ConfigFlow, ConfigFlowResult
from homeassistant.const import CONF_IP_ADDRESS, CONF_WEBHOOK_ID

from .const import DOMAIN

_LOGGER = logging.getLogger(__name__)

SONIC = "Sonic"
WATERGATE_SCHEMA = vol.Schema(
    {
        vol.Required(CONF_IP_ADDRESS): str,
    }
)


class WatergateConfigFlow(ConfigFlow, domain=DOMAIN):
    """Watergate config flow."""

    async def async_step_user(
        self, user_input: dict[str, str] | None = None
    ) -> ConfigFlowResult:
        """Handle a flow initiated by the user."""
        errors: dict[str, str] = {}
        if user_input is not None:
            ip_address = user_input[CONF_IP_ADDRESS]

            # Validate that the IP address starts with 'http://'
            if not ip_address.startswith("http://"):
                errors[CONF_IP_ADDRESS] = "invalid_format"
            elif not await self.validate_connection(ip_address):
                errors[CONF_IP_ADDRESS] = "cannot_connect"
            else:
                return self.async_create_entry(
                    data={**user_input, CONF_WEBHOOK_ID: webhook_generate_id()},
                    title=SONIC,
                )

        return self.async_show_form(
            step_id="user", data_schema=WATERGATE_SCHEMA, errors=errors
        )

    async def validate_connection(self, ip_address: str):
        """Validate the connection to the Watergate device."""
        try:
            return (
                await WatergateLocalApiClient(ip_address).async_get_device_state()
                is not None
            )
        except WatergateApiException as exception:
            _LOGGER.error("Error connecting to Watergate device: %s", exception)
            return False
```

than adding to strings.json such that 

```
{
  "config": {
    "step": {
      "user": {
        "data": {
          "ip_address": "[%key:common::config_flow::data::ip%]"
        },
        "title": "Configure Watergate device",
        "data_description": {
          "ip_address": "Provide an IP address of your Watergate device."
        }
      }
    },
    "error": {
      "cannot_connect": "[%key:common::config_flow::error::cannot_connect%]",
      "invalid_format": "The IP address must start with 'http://'. Please correct it."
    }
  }
}
```

**Comment by siobhanellis** [comment]
I’d prefer ip address and you add the http:// in your code. It’s less typing for the user….. or another way is you could sniff the network and find it 😊

It’s also best to use network name rather than ip address as most people do not reserve ip addresses as they have local DHCP.

Thanks

Siobhan

IOT: Practical HomeKit: ( https://practicalhomekit.blogspot.com )
Charity Fundraising: Lammie Drive: ( lammiedrive.blogspot.com<http://lammiedrive.blogspot.com/> )


From: Nivek1612 ***@***.***>
Date: Wednesday, 27 November 2024 at 07:04
To: watergate-ai/watergate-ha-custom-component ***@***.***>
Cc: siobhanellis ***@***.***>, Author ***@***.***>
Subject: Re: [watergate-ai/watergate-ha-custom-component] IP address is actually web address (Issue #6)

Yes that needs to be addressed either in docs or handled in the setup code. @adam-the-hero<https://github.com/adam-the-hero> I can take a look if you like just let me know your preference.

**Comment by slash-drumbler** [comment]
Hi all,

I wonder if anyone could point out where I am going wrong in getting set up.

Local mode status is enabled in the app, I have reserved an IP for the device and have tried both with http:// and without, restarted Home Assistant etc but it keeps failing to connect.

HA logs:

This error originated from a custom integration.

Logger: custom_components.watergate.config_flow
Source: custom_components/watergate/config_flow.py:56
integration: Watergate
First occurred: 11:47:50 (1 occurrences)
Last logged: 11:47:50

Error connecting to Watergate device: Failed to fetch data from http://10.27.27.8/api/sonic/ after 3 attempts

Any ideas on what I am doing wrong?

Cheers,
Sean

**Comment by nivek1612** [comment]
If you are confident the sonic is on the IP address you shared then try typing this in the web address of your preferred browser 

http://10.27.27.8/api/sonic/

What happens

**Comment by slash-drumbler** [comment]
Confident IP address is correct. Hostname is listed as HERO in my leases and I cannot see any other IP Address listed that it could be.

Going to http://10.27.27.8/api/sonic/ in my browser just gives me a connection refused error

**Comment by nivek1612** [comment]
And HA and sonic are on the same subnet/VLAN ?

**Comment by slash-drumbler** [comment]
Correct, same subnet/VLAN.

Could it be a problem with the HERO local mode?

**Comment by nivek1612** [comment]
Sounds that way but let’s dig a little 

what do you see in the app should be something like this 
![IMG_5829](https://github.com/user-attachments/assets/79411d1f-b7be-4ca8-897e-57168efa2176)

**Comment by slash-drumbler** [comment]
I do not have the local API or WiFi options under Sonic settings:
![Screenshot_20241201-133452](https://github.com/user-attachments/assets/2327ba56-46bd-4598-b70b-97e28d970781)

WiFi options are showing in the Bridge settings. I have just updated the app and have noticed the Local Mode Status option has now disappeared completely: 
![Screenshot_20241201-133511](https://github.com/user-attachments/assets/9c8ad05f-5f9e-4ee4-9efc-eb5e6b67c4fd)

Could I be missing a firmware update?

**Comment by nivek1612** [comment]
Ah you have the Sonic Pro
I don’t believe the firmware has been released for that model yet 
The current set up is for the Sonic WiFi only

maybe a question for support when they are back online on Monday

**Comment by slash-drumbler** [comment]
Oh is that what the issue is!

Perhaps I missed it, but I couldn't see any documentation saying that not all models are supported yet. I'll contact support!

Thanks for all your help mate!

**Comment by adam-the-hero** [comment]
@nivek1612, @siobhanellis I've just added http to the address. @nivek1612 your first approach was better and most commonly used in other HA intergations. You can guys review the PR and we will merge it and release that change.
