### ISSUE TITLE
Can't connect to energy dash board

### ISSUE THREAD

**Issue by siobhanellis** [watergate-ai/watergate-ha-custom-component#7]
The energy dashboard requires a device class of "water", you have a device class of "volume" which means we can't connect the device to the energy dashboard.

We either need the device changed, or we need documentation on creating a helper to add Watergate sonic to the energy dashboard.

**Comment by nivek1612** [comment]
Already solved via https://github.com/watergate-ai/watergate-ha-custom-component/commit/c5115cc349944dfe7366ade4ec95114592be1d95

did you update recently ?

**Comment by siobhanellis** [comment]
I did, after I logged the problem.

Works now.

Siobhan

IOT: Practical HomeKit: ( https://practicalhomekit.blogspot.com )
Charity Fundraising: Lammie Drive: ( lammiedrive.blogspot.com<http://lammiedrive.blogspot.com/> )


From: Nivek1612 ***@***.***>
Date: Wednesday, 27 November 2024 at 07:01
To: watergate-ai/watergate-ha-custom-component ***@***.***>
Cc: siobhanellis ***@***.***>, Author ***@***.***>
Subject: Re: [watergate-ai/watergate-ha-custom-component] Can't connect to energy dash board (Issue #7)

Already solved via c5115cc<https://github.com/watergate-ai/watergate-ha-custom-component/commit/c5115cc349944dfe7366ade4ec95114592be1d95>

did you update recently ?
